### ISSUE TITLE
Is it possible to publish simulacrum-scalafix-annotations for Scala.js 0.6?

### ISSUE THREAD

**Issue by takayahilton** [typelevel/simulacrum-scalafix#41]
`simulacrum-scalafix` is ​​not available from scala.js 0.6 project now.

**Comment by travisbrown** [comment]
Cross-publishing for Scala.js 0.6 and 1.x is a headache, and I'm reluctant to reintroduce it, especially for a project like this one that's primarily going to be used in other libraries, which should be encouraged to upgrade to 1.x as quickly as possible. If it's absolutely necessary it should be possible to mix versions—e.g. to use 0.5.0 for the rules and 0.1.0 (which I believe is the last cross-published release) for the annotations.

**Comment by takayahilton** [comment]
Thank you.
I will use the mixed version.
