### ISSUE TITLE
Use end marker?

### ISSUE THREAD

**Issue by nafg** [typelevel/simulacrum-scalafix#6]
Maybe it would be better to add an end marker rather than going from the comment to the end of the object, this way it would be possible to have multiple scalafix rules that add things to an object (for instance, monocle `@Lenses`)?

**Comment by travisbrown** [comment]
Yes, I've got a branch for this (plus a little more parametrization around the banners in general), and will open a PR soon.

**Comment by travisbrown** [comment]
Added in #8.
